services:
  pipeline:
    build: .
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
      # Optional: Code-Mapping f√ºr schnellere Entwicklung
      - ./src:/app/src
      - ./main.py:/app/main.py
    depends_on:
      - db

  enricher:
    build: .
    env_file:
      - ./.env
    command: ["python", "enrich_facilities.py"]
    volumes:
      # Optional: Code-Mapping
      - ./src:/app/src
      - ./enrich_facilities.py:/app/enrich_facilities.py
      - ./data:/app/data # Falls das Skript den Cache liest/schreibt
    depends_on:
      - db

  tester: # NEUER Service
    build: .
    env_file:
      - ./.env
    command: ["python", "-m", "unittest", "discover", "tests"]
    working_dir: /app
    volumes:
      # Code-Mapping, damit aktuelle Tests verwendet werden
      - ./src:/app/src
      - ./tests:/app/tests
      - ./main.py:/app/main.py
      - ./enrich_facilities.py:/app/enrich_facilities.py
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: