name: Deploy Sphinx Docs to GitHub Pages

on:
  # Wird ausgeführt bei jedem Push auf den master-Branch
  push:
    branches: [ "master" ] # Ändere dies zu "main"
  pull_request:
    branches: ["master"]

# Berechtigungen für das Deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Installiere Projekt-Abhängigkeiten (für Autodoc)
        run: pip install -r requirements.txt

      - name: Installiere Sphinx-Abhängigkeiten
        run: pip install sphinx furo sphinx-design

      - name: Baue die HTML-Seiten
        run: |
          python -m sphinx -E -a -b html docs docs/_build/html

      - name: Lade Artefakt hoch
        # Lädt die gebauten HTML-Seiten hoch
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_build/html'

      - name: Deploy auf GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4